version: "3.8"

services:
  loki:
    image: grafana/loki:3.4.2
    container_name: loki
    restart: always
    volumes:
      - ./config/loki-config.yaml:/etc/loki/loki-config.yaml
      - loki_data:/loki
    ports:
      - "3100:3100"
    networks:
      - alumni-network
    command: -config.file=/etc/loki/loki-config.yaml

  promtail:
    image: grafana/promtail:3.4.2
    container_name: promtail
    networks:
      - alumni-network
    volumes:
      - ./config/promtail-config.yaml:/etc/promtail/config.yaml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    command: -config.file=/etc/promtail/config.yaml
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
        mode: non-blocking
        max-buffer-size: 4m
        loki-retries: "3"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_SERVER_DOMAIN=http://localhost/monitor/
      - GF_SERVER_ROOT_URL=http://localhost/monitor/
    depends_on:
      - loki
    volumes:
      - ./config/loki-datasource.yml:/etc/grafana/provisioning/datasources/loki-datasource.yml
    ports:
      - "3000:3000"
    networks:
      - alumni-network
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
        mode: non-blocking
        max-buffer-size: 4m
        loki-retries: "3"

  neo4j:
    image: neo4j:5.26.4
    container_name: neo4j
    restart: always
    environment:
      - NEO4J_AUTH=${NEO4J_LOCAL_USERNAME}/${NEO4J_LOCAL_CONTAINER_PASSWORD}
      - NEO4JLABS_PLUGINS=["apoc"]
      - NEO4J_apoc_import_file_enabled="true"
      - NEO4J_apoc_export_file_enabled="true"
      - NEO4J_apoc_import_file_use__neo4j__config="true"
    ports:
      - "7687:7687"
      - "7474:7474"
    volumes:
      - ~/neo4j/data:/data
    networks:
      - alumni-network
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
        mode: non-blocking
        max-buffer-size: 4m
        loki-retries: "3"

  alumni-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: alumni-frontend
    restart: always
    ports:
      - "5173:5173"
    networks:
      - alumni-network

  api-blue:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: alumni-api-blue
    restart: unless-stopped
    environment:
      - DB_ENV=${DB_ENV}
      - NEO4J_LOCAL_URI=${NEO4J_LOCAL_CONTAINER_URI}
      - NEO4J_LOCAL_USERNAME=${NEO4J_LOCAL_USERNAME}
      - NEO4J_LOCAL_PASSWORD=${NEO4J_LOCAL_CONTAINER_PASSWORD}
      - NEO4J_AURA_URI=${NEO4J_AURA_URI}
      - NEO4J_AURA_USERNAME=${NEO4J_AURA_USERNAME}
      - NEO4J_AURA_PASSWORD=${NEO4J_AURA_PASSWORD}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - AES_ENCRYPTION_KEY=${AES_ENCRYPTION_KEY}
      - SENDER_GMAIL=${SENDER_GMAIL}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - PORT=${PORT}
      - ENV=${ENV}
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/v1 || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 3
    networks:
      - alumni-network
    volumes:
      - ./uploads:/app/uploads
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
        mode: non-blocking
        max-buffer-size: 4m
        loki-retries: "3"

  api-green:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: alumni-api-green
    restart: unless-stopped
    environment:
      - DB_ENV=${DB_ENV}
      - NEO4J_LOCAL_URI=${NEO4J_LOCAL_CONTAINER_URI}
      - NEO4J_LOCAL_USERNAME=${NEO4J_LOCAL_USERNAME}
      - NEO4J_LOCAL_PASSWORD=${NEO4J_LOCAL_CONTAINER_PASSWORD}
      - NEO4J_AURA_URI=${NEO4J_AURA_URI}
      - NEO4J_AURA_USERNAME=${NEO4J_AURA_USERNAME}
      - NEO4J_AURA_PASSWORD=${NEO4J_AURA_PASSWORD}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - AES_ENCRYPTION_KEY=${AES_ENCRYPTION_KEY}
      - SENDER_GMAIL=${SENDER_GMAIL}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - PORT=${PORT}
      - ENV=${ENV}
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/v1 || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 3
    networks:
      - alumni-network
    volumes:
      - ./uploads:/app/uploads
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
        mode: non-blocking
        max-buffer-size: 4m
        loki-retries: "3"

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    # depends_on:
    #   - api
    ports:
      - "80:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./scripts/switch-color.sh:/scripts/switch-color.sh
    networks:
      - alumni-network
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
        mode: non-blocking
        max-buffer-size: 4m
        loki-retries: "3"

volumes:
  neo4j_data:
  loki_data:

networks:
  alumni-network:
    driver: bridge
